<?php

return [
    'smb' => [
        'host' => env('SMB_HOST', 'meganas'),
        'share' => env('SMB_SHARE', 'Video'),
        'path' => env('SMB_PATH', 'Movies'),
        'username' => env('SMB_USERNAME', ''),
        'password' => env('SMB_PASSWORD', ''),
        'backend' => env('SMB_BACKEND', 'auto'),
        'workgroup' => env('SMB_WORKGROUP', ''),
        'binary' => env('SMBCLIENT_BIN', 'smbclient'),
        'config_file' => env('SMBCLIENT_CONFIG_FILE', ''),
        'timeout_seconds' => (int) env('SMB_TIMEOUT_SECONDS', 180),
        'video_extensions' => [
            'mkv',
            'mp4',
            'avi',
            'mov',
            'wmv',
            'm4v',
            'ts',
            'mpg',
            'mpeg',
            'divx',
            'xvid',
            'flv',
            'webm',
        ],
    ],
    'tmdb' => [
        'provider' => env('TMDB_PROVIDER', 'http'),
        'api_key' => env('TMDB_API_KEY'),
        'token' => env('TMDB_TOKEN'),
        'preferred_language' => env('TMDB_PREFERRED_LANGUAGE', 'ru-RU'),
        'search_include_adult' => (bool) env('TMDB_SEARCH_INCLUDE_ADULT', false),
        'search_region' => env('TMDB_SEARCH_REGION'),
        'base_url' => env('TMDB_BASE_URL', 'https://api.themoviedb.org/3'),
        'details_append_to_response' => env(
            'TMDB_DETAILS_APPEND_TO_RESPONSE',
            'alternative_titles,credits,external_ids,images,keywords,release_dates,recommendations,similar,translations,videos,watch/providers',
        ),
        'details_include_image_language' => env('TMDB_DETAILS_INCLUDE_IMAGE_LANGUAGE', 'null,en'),
        'cache_days' => (int) env('TMDB_CACHE_DAYS', 7),
        'requests_per_window' => (int) env('TMDB_RATE_MAX_REQUESTS', 40),
        'window_seconds' => (int) env('TMDB_RATE_WINDOW_SECONDS', 10),
        'match_threshold' => (float) env('TMDB_MATCH_THRESHOLD', 0.75),
        'uncertain_threshold' => (float) env('TMDB_UNCERTAIN_THRESHOLD', 0.55),
        'mcp_enabled' => (bool) env('TMDB_MCP_ENABLED', false),
        'mcp_http_fallback' => (bool) env('TMDB_MCP_HTTP_FALLBACK', true),
        'mcp_command' => env('TMDB_MCP_COMMAND', ''),
        'mcp_timeout_seconds' => (int) env('TMDB_MCP_TIMEOUT_SECONDS', 30),
        'mcp_search_tools' => env('TMDB_MCP_SEARCH_TOOLS', 'search_movies,search_movie,movie_search,find_movie,two_actors_on_screen,two_people,two_movies,filmography_actor_genre,filmography_crew_genre'),
        'mcp_movie_tools' => env('TMDB_MCP_MOVIE_TOOLS', 'get_movie_details,get_movie,movie_details'),
        'mcp_resource_uris' => env('TMDB_MCP_RESOURCE_URIS', 'tmdb://movie/{id},tmdb:///movie/{id},tmdb://movie/{id}?language={language}'),
        'mcp_cache_hours' => (int) env('TMDB_MCP_CACHE_HOURS', 12),
        'mcp_uv_cache_dir' => env('TMDB_MCP_UV_CACHE_DIR', storage_path('framework/cache/mcp-uv')),
    ],
    'scan' => [
        'progress_cache_key' => 'cineclean.scan.progress',
        'start_flag_cache_key' => 'cineclean.scan.requested',
        'cache_ttl_minutes' => 360,
    ],
    'files' => [
        'allow_delete' => (bool) env('MOVIESANALYZER_ALLOW_DELETE', env('CINECLEAN_ALLOW_DELETE', false)),
    ],
];
